# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientInterface.ui'
#
# Created by: PyQt6 UI code generator 6.x.x
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        
        # Top Bar
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.hostname = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.hostname.setObjectName("hostname")
        self.horizontalLayout.addWidget(self.hostname)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.username.setObjectName("username")
        self.horizontalLayout.addWidget(self.username)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setObjectName("password")
        self.horizontalLayout.addWidget(self.password)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.port = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.port.setMaximumSize(QtCore.QSize(60, 16777215))
        self.port.setObjectName("port")
        self.horizontalLayout.addWidget(self.port)
        self.loginButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout.addWidget(self.loginButton)
        self.logoutButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.logoutButton.setObjectName("logoutButton")
        self.horizontalLayout.addWidget(self.logoutButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        
        # Connection Status Panel (below login bar)
        self.statusPanel = QtWidgets.QWidget(parent=self.centralwidget)
        self.statusPanel.setMaximumSize(QtCore.QSize(16777215, 60))
        self.statusPanel.setObjectName("statusPanel")
        self.statusPanelLayout = QtWidgets.QHBoxLayout(self.statusPanel)
        self.statusPanelLayout.setContentsMargins(5, 5, 5, 5)
        self.statusPanelLayout.setObjectName("statusPanelLayout")
        
        self.connectionStatusLabel = QtWidgets.QLabel(parent=self.statusPanel)
        self.connectionStatusLabel.setObjectName("connectionStatusLabel")
        self.statusPanelLayout.addWidget(self.connectionStatusLabel)
        
        self.transferStatusLabel = QtWidgets.QLabel(parent=self.statusPanel)
        self.transferStatusLabel.setObjectName("transferStatusLabel")
        self.statusPanelLayout.addWidget(self.transferStatusLabel)
        
        self.currentTransferLabel = QtWidgets.QLabel(parent=self.statusPanel)
        self.currentTransferLabel.setObjectName("currentTransferLabel")
        self.statusPanelLayout.addWidget(self.currentTransferLabel)
        
        self.transferProgressBar = QtWidgets.QProgressBar(parent=self.statusPanel)
        self.transferProgressBar.setProperty("value", 0)
        self.transferProgressBar.setObjectName("transferProgressBar")
        self.statusPanelLayout.addWidget(self.transferProgressBar)
        
        self.verticalLayout.addWidget(self.statusPanel)
        
        # Log Window
        self.statusWindow = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.statusWindow.setMaximumSize(QtCore.QSize(16777215, 100))
        self.statusWindow.setObjectName("statusWindow")
        self.statusWindow.setColumnCount(0)
        self.statusWindow.setRowCount(0)
        self.verticalLayout.addWidget(self.statusWindow)
        
        # Splitter
        self.splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        
        # Local Side
        self.layoutWidget = QtWidgets.QWidget(parent=self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.localPath = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.localPath.setEditable(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localPath.sizePolicy().hasHeightForWidth())
        self.localPath.setSizePolicy(sizePolicy)
        self.localPath.setObjectName("localPath")
        self.horizontalLayout_3.addWidget(self.localPath)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        
        self.localdir = QtWidgets.QTreeView(parent=self.layoutWidget)
        self.localdir.setObjectName("localdir")
        self.verticalLayout_2.addWidget(self.localdir)
        
        # Remote Side
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.splitter)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.remotePath = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.remotePath.setReadOnly(True)
        self.remotePath.setObjectName("remotePath")
        self.horizontalLayout_4.addWidget(self.remotePath)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        
        self.remoteSplitter = QtWidgets.QSplitter(parent=self.layoutWidget_2)
        self.remoteSplitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.remoteSplitter.setObjectName("remoteSplitter")
        
        self.remoteTree = QtWidgets.QTreeWidget(parent=self.remoteSplitter)
        self.remoteTree.setHeaderHidden(True)
        self.remoteTree.setObjectName("remoteTree")
        self.remoteTree.headerItem().setText(0, "Remote Site")
        
        self.remotedir = QtWidgets.QTableWidget(parent=self.remoteSplitter)
        self.remotedir.setObjectName("remotedir")
        self.remotedir.setColumnCount(0)
        self.remotedir.setRowCount(0)
        
        self.verticalLayout_3.addWidget(self.remoteSplitter)
        
        self.verticalLayout.addWidget(self.splitter)
        
        # Bottom Tabs
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tabWidget.setObjectName("tabWidget")
        
        # Tab 1: Queue Files
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabLayout = QtWidgets.QVBoxLayout(self.tab)
        self.tabLayout.setContentsMargins(0, 0, 0, 0)
        self.queueTable = QtWidgets.QTableWidget(parent=self.tab)
        self.queueTable.setObjectName("queueTable")
        self.queueTable.setColumnCount(6)
        self.queueTable.setHorizontalHeaderLabels(["文件名", "方向", "状态", "进度", "大小", "速度"])
        self.queueTable.horizontalHeader().setStretchLastSection(True)
        self.tabLayout.addWidget(self.queueTable)
        self.tabWidget.addTab(self.tab, "")
        
        # Tab 2: Failed Transfers
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tab2Layout = QtWidgets.QVBoxLayout(self.tab_2)
        self.tab2Layout.setContentsMargins(0, 0, 0, 0)
        self.failedTable = QtWidgets.QTableWidget(parent=self.tab_2)
        self.failedTable.setObjectName("failedTable")
        self.failedTable.setColumnCount(5)
        self.failedTable.setHorizontalHeaderLabels(["文件名", "方向", "大小", "错误信息", "时间"])
        self.failedTable.horizontalHeader().setStretchLastSection(True)
        self.tab2Layout.addWidget(self.failedTable)
        self.tabWidget.addTab(self.tab_2, "")
        
        # Tab 3: Successful Transfers
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tab3Layout = QtWidgets.QVBoxLayout(self.tab_3)
        self.tab3Layout.setContentsMargins(0, 0, 0, 0)
        self.successTable = QtWidgets.QTableWidget(parent=self.tab_3)
        self.successTable.setObjectName("successTable")
        self.successTable.setColumnCount(5)
        self.successTable.setHorizontalHeaderLabels(["文件名", "方向", "大小", "平均速度", "完成时间"])
        self.successTable.horizontalHeader().setStretchLastSection(True)
        self.tab3Layout.addWidget(self.successTable)
        self.tabWidget.addTab(self.tab_3, "")
        
        self.verticalLayout.addWidget(self.tabWidget)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FTP Client"))
        self.label.setText(_translate("MainWindow", "主机(H):"))
        self.hostname.setText(_translate("MainWindow", "127.0.0.1"))
        self.label_2.setText(_translate("MainWindow", "用户名(U):"))
        self.label_3.setText(_translate("MainWindow", "密码(W):"))
        self.label_4.setText(_translate("MainWindow", "端口(P):"))
        self.port.setText(_translate("MainWindow", "21"))
        self.loginButton.setText(_translate("MainWindow", "快速连接(Q)"))
        self.logoutButton.setText(_translate("MainWindow", "断开"))
        self.connectionStatusLabel.setText(_translate("MainWindow", "连接状态: 未连接"))
        self.transferStatusLabel.setText(_translate("MainWindow", "传输状态: 空闲"))
        self.currentTransferLabel.setText(_translate("MainWindow", ""))
        self.label_6.setText(_translate("MainWindow", "本地站点:"))
        self.label_7.setText(_translate("MainWindow", "远程站点:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "队列的文件"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "传输失败"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "成功的传输"))
